name: Daily SS.LV Real Estate Monitor

on:
  schedule:
    # Run daily at 8:00 AM UTC (adjust time as needed)
    - cron: '0 8 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 requests schedule
        
    - name: Run SS.LV monitor
      env:
        EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
      run: python ss_lv_monitor.py
      
    - name: Upload listings data
      uses: actions/upload-artifact@v4
      with:
        name: listings-data
        path: listings_data.json
        retention-days: 30
